"""System memory: patterns learned from past trade outcomes.

Stored in data/memory.json as a list of records, each tagged with a `source`:
  - "seed" : hand-written priors that ship with the app
  - "auto" : regenerated by the learning system from closed-trade stats
  - "user" : added manually via `--remember`
This is rendered into the SYSTEM MEMORY section of the prompt so the analyst can
weight past performance. The learning system replaces only the "auto" records,
leaving seed and user notes intact.
"""

import json

import config

_DEFAULT = [
    {
        "source": "seed",
        "pattern": "Trades taken with confidence below 7 or fewer than 4 agreeing sources",
        "outcome": "Historically low win rate. Do not trade these.",
    },
    {
        "source": "seed",
        "pattern": "Entering right before a high-impact data release (NFP, CPI, central bank decision)",
        "outcome": "Whipsaw risk is severe; edge from analysis is overwhelmed by event volatility.",
    },
    {
        "source": "seed",
        "pattern": "Technical signal conflicts with the interest-rate differential direction",
        "outcome": "Mixed results - fundamentals tend to win over weeks. Lower confidence on such conflicts.",
    },
]


def load() -> list:
    if not config.MEMORY_FILE.exists():
        save(_DEFAULT)
        return list(_DEFAULT)
    try:
        records = json.loads(config.MEMORY_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return list(_DEFAULT)
    for r in records:  # backfill source on older files
        r.setdefault("source", "user")
    return records


def save(records: list) -> None:
    config.MEMORY_FILE.write_text(json.dumps(records, indent=2), encoding="utf-8")


def add_outcome(pattern: str, outcome: str) -> None:
    records = load()
    records.append({"source": "user", "pattern": pattern, "outcome": outcome})
    save(records)


def set_auto_patterns(patterns: list) -> None:
    """Replace all source=='auto' records with a fresh set from the learning system.
    `patterns` is a list of {"pattern": ..., "outcome": ...} dicts."""
    kept = [r for r in load() if r.get("source") != "auto"]
    for p in patterns:
        kept.append({"source": "auto", "pattern": p["pattern"], "outcome": p["outcome"]})
    save(kept)


def render() -> str:
    records = load()
    if not records:
        return "SYSTEM MEMORY: (empty - no learned patterns yet)"
    lines = ["SYSTEM MEMORY - patterns learned from past outcomes (weight heavily):"]
    for i, r in enumerate(records, 1):
        tag = r.get("source", "user").upper()
        lines.append(f"  {i}. [{tag}] PATTERN: {r.get('pattern')}")
        lines.append(f"     OUTCOME: {r.get('outcome')}")
    return "\n".join(lines)
